camera: use RELAX_USES_LIBRARY_CHECK for prebuilt camera
FAILED: out/target/common/obj/APPS/CamearGo_intermediates/enforce_uses_libraries.status
/bin/bash -c "(rm -f out/target/common/obj/APPS/CamearGo_intermediates/enforce_uses_libraries.status ) && (build/soong/scripts/manifest_check.py 	  --enforce-us
es-libraries 	  --enforce-uses-libraries-status out/target/common/obj/APPS/CamearGo_intermediates/enforce_uses_libraries.status 	  --aapt out/host/linux-x86/bi
n/aapt 	   	   	   	   	  vendor/google/Camera/CamearGo/CamearGo.apk )"
error: mismatch in the <uses-library> tags between the build system and the manifest:
	- required libraries in build system: []
	                 vs. in the manifest: []
	- optional libraries in build system: []
	                 vs. in the manifest: [androidx.window.extensions, androidx.window.sidecar]
	- tags in the manifest (vendor/google/Camera/CamearGo/CamearGo.apk):
		uses-library-not-required:'androidx.window.extensions'		uses-library-not-required:'androidx.window.sidecar'
note: the following options are available:
	- to temporarily disable the check on command line, rebuild with RELAX_USES_LIBRARY_CHECK=true (this will set compiler filter "verify" and disable AOT-compila
tion in dexpreopt)
	- to temporarily disable the check for the whole product, set PRODUCT_BROKEN_VERIFY_USES_LIBRARIES := true in the product makefiles
	- to fix the check, make build system properties coherent with the manifest
	- see build/make/Changes.md for details